"""
This type stub file was generated by pyright.
"""

from argparse import ArgumentParser
from nbtlib.tag import Compound

def nbt_data(literal) -> Compound: ...

parser: ArgumentParser
inputs: ArgumentParser
outputs: ArgumentParser

def main() -> None: ...
def read(
    filename: str, gzipped: bool, byteorder, snbt, path, find
) -> Generator[Any | list[Any] | File, Any, None]: ...
def display(tag, compact, pretty, unpack, json) -> None: ...
def write(nbt_data, filename: str, gzipped: bool, byteorder) -> None: ...
def merge(nbt_data, filename: str, gzipped: bool, byteorder) -> None: ...
