"""
This type stub file was generated by pyright.
"""

Coordinate = tuple[int, int, int]
def block_is_in_box(block: Coordinate, box: tuple[Coordinate, Coordinate]) -> bool:
    """
    Returns True id the block is in the box
    block is (x, y, z)
    box is ((x0, y0, z0), (x1, y1, z1))
    """
    ...

def box_is_in_box(box1: tuple[Coordinate, Coordinate], box2: tuple[Coordinate, Coordinate]) -> bool:
    ...

