"""
This type stub file was generated by pyright.
"""

from nbtlib.tag import Base, Compound
from typing_extensions import deprecated
from .deprecation import deprecated_name
from .storage import DiscriminatingDictionary
from typing import Iterable, Optional, Union

EntityPosition = tuple[float, float, float]
EntityRotation = tuple[float, float]
EntityMotion = tuple[float, float, float]
BlockPosition = tuple[int, int, int]

class BlockState:
    """
    Represents an in-game block.
    :class:`BlockState` are immutable.
    """

    __block_id: str
    __properties: DiscriminatingDictionary
    __identifier_cache: Optional[str]
    def __init__(self, block_id: str, **properties: str) -> None:
        """
        A block state has a block ID and a dictionary of properties.

        :param block_id:    the identifier of the block (e.g. *minecraft:stone*)
        :param properties:  the properties of the block state as keyword parameters (e.g. *facing="north"*)
        """
        ...

    def to_nbt(self) -> Compound:
        """
        Writes this block state to an nbt tag.
        """
        ...

    @deprecated_name("fromnbt")
    @staticmethod
    def from_nbt(nbt: Compound) -> BlockState:
        """
        Reads a :class:`BlockState` from an nbt tag.
        """
        ...

    @property
    def id(self) -> str:
        """
        The block's identifier.
        """
        ...

    @property
    @deprecated("Use BlockState.id instead")
    def blockid(self) -> str: ...
    @deprecated_name("with_blockid")
    def with_id(self, block_id: str) -> BlockState:
        """
        Returns a new :class:`BlockState` with the same properties as this one but a different block id.

        :param block_id:  the block id for the new :class:`BlockState`
        """
        ...

    def with_properties(self, **properties: Optional[str]) -> BlockState:
        """
        Returns a new copy of this :class:`BlockState` with new values for the properties given in keyword arguments.
        Using `None` as a property value removes it.

        :param properties:  the new properties as keyword arguments

        :returns: A copy of this :class:`BlockState` with the given properties updated to new values
        """
        ...

    def properties(self) -> Iterable[tuple[str, str]]:
        """
        Exposes the properties of this :class:`BlockState` using an iterator over its properties, in a similar fashion as :func:`dict.items()`.

        :returns: An iterable over the properties, as property, value tuples.
        """
        ...

    def to_block_state_identifier(self, skip_empty: bool = ...) -> str:
        """
        Returns an identifier that represents the BlockState in the Sponge Schematic Format (version 2).
        Format: block_type[properties]
        Example: minecraft:oak_sign[rotation=0,waterlogged=false]

        :param skip_empty:  Whether empty brackets should be excluded if the BlockState has no properties.

        :returns: An identifier that represents the BlockState in a Sponge schematic.
        """
        ...

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Optional[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...

class Entity:
    """
    A Minecraft entity.
    Each entity is identified by a type identifier (e.g. minecraft:skeleton)
    and has a position within a region, as well as a rotation and a velocity vector.
    Most also have arbitrary data depending on their type
    (e.g. a sheep has a tag for its color and one indicating whether it has been sheared).
    """

    _id: str
    _data: Compound
    _position: EntityPosition
    _rotation: EntityRotation
    _motion: EntityMotion
    def __init__(self, str_or_nbt: Union[str, Compound]) -> None:
        """
        :param str_or_nbt:  either the entity identifier as a string, in which case all other tag will be default,
                            or an bnt compound tag with the entitie's data.
        """
        ...

    def to_nbt(self) -> Compound:
        """
        Save this entity as an NBT tag.
        """
        ...

    @deprecated_name("fromnbt")
    @staticmethod
    def from_nbt(nbt: Compound) -> Entity:
        """
        Read an entity from an nbt tag.

        :param nbt: An NBT tag with the entity's data
        """
        ...

    def add_tag(self, key: str, tag) -> None: ...
    def get_tag(self, key: str) -> Base: ...
    @property
    def data(self) -> Compound: ...
    @data.setter
    def data(self, data: Compound) -> None: ...
    @property
    def id(self) -> str:
        """
        This entity's type identifier (e.g. *minecraft:pig* )
        """
        ...

    @id.setter
    def id(self, id: str) -> None: ...
    @property
    def position(self) -> EntityPosition:
        """
        The position of the entity.
        """
        ...

    @position.setter
    def position(self, position: EntityPosition) -> None: ...
    @property
    def rotation(self) -> EntityRotation:
        """
        The rotation of the entity.
        """
        ...

    @rotation.setter
    def rotation(self, rotation: EntityRotation) -> None: ...
    @property
    def motion(self) -> EntityMotion:
        """
        The velocity vector of the entity.
        """
        ...

    @motion.setter
    def motion(self, motion: EntityMotion) -> None: ...

class TileEntity:
    """
    A tile entity, also often referred to as block entities,
    is a type of entity which complements a block state to store additional data
    (e.g. containers like chest both have a block state that stores properties
    like their id ( *minecraft:chest* ) and orientation, and tile entity that stores their content.
    For this reason, the :class:`TileEntity` class does not store an ID  but only a position.
    The ID can be inferred by looking up the :class:`BlockState` as the same position in the :class:`Region`.
    """

    _data: Compound
    _position: BlockPosition
    def __init__(self, nbt: Compound) -> None: ...
    def to_nbt(self) -> Compound:
        """
        Saves the tile entity to NBT tag.
        """
        ...

    @deprecated_name("fromnbt")
    @staticmethod
    def from_nbt(nbt: Compound) -> TileEntity:
        """
        Reads a tile entity from an NBT tag.

        :param nbt: the tile entity's data as an NBT tag
        """
        ...

    def add_tag(self, key: str, tag) -> None: ...
    def get_tag(self, key: str) -> Base: ...
    @property
    def data(self) -> Compound: ...
    @data.setter
    def data(self, data: Compound):  # -> None:
        ...
    @property
    def position(self) -> BlockPosition:
        """
        The tile entity's position within the :class:`Region`/
        """
        ...

    @position.setter
    def position(self, position: BlockPosition):  # -> None:
        ...

def is_valid_identifier(identifier: str) -> bool:
    """
    Checks if a string is a valid identifier (aka. ResourceLocation in Mojmap).
    """
    ...

class InvalidIdentifier(ValueError):
    identifier: str
    def __init__(self, identifier: str) -> None: ...

def assert_valid_identifier(identifier: str) -> str:
    """
    Checks whether a string is a valid identifier (aka  ResourceLocation in Mojmap),
    and raises InvalidIdentifierError if it is not.
    The name "identifier" is from Yarn mappings but makes more sens in this context.

    :returns: the identifier
    :raises CorruptedSchematicError: if provided string is not a valid identifier
    """
    ...

class RequiredKeyMissingException(Exception):
    def __init__(self, key: str, message: str = ...) -> None: ...
    def __str__(self) -> str: ...
