"""
This type stub file was generated by pyright.
"""

import nbtlib
import numpy as np
from nbtlib.tag import Compound, IntArray
from typing_extensions import deprecated
from typing import Any, Callable, Generator, Optional
from .deprecation import deprecated_name
from .minecraft import BlockState, Entity, TileEntity
from .storage import DiscriminatingDictionary

class Schematic:
    """
    Represents a schematic file in the Litematic format.
    """

    name: str
    author: str
    description: str
    region: dict[str, Region]
    lm_version: int
    lm_subversion: int
    mc_version: int
    created: int
    modified: int
    __regions: DiscriminatingDictionary
    __preview: IntArray
    def __init__(
        self,
        name: str = ...,
        author: str = ...,
        description: str = ...,
        regions: Optional[dict[str, Region]] = ...,
        lm_version: int = ...,
        lm_subversion: int = ...,
        mc_version: int = ...,
    ) -> None:
        """
        Schematic can be created by optionally providing metadata and regions, or leaving them blank or default.

        :param name:        The name of the schematic to write in the metadata
        :param author:      The name of the author to write in the metadata
        :param description: The description to write in the metadata
        :param regions:     Regions to populate the schematic with
        :param lm_version:  The litematic version (you are unlikely to ever need to use this)
        :param mc_version:  The Minecraft data version (you are unlikely to ever need to use this)
        """
        ...

    def save(
        self,
        file_path: str,
        update_meta: bool = ...,
        save_soft: bool = ...,
        gzipped: bool = ...,
        byteorder: str = ...,
    ) -> None:
        """
        Save this schematic to a file.

        :param file_path:   the filesystem path the schematic should be saved to
        :param update_meta: whether to update the schematic's metadata before saving
                            (see :func:`~litemapy.Schematic.update_metadata`)
        :param save_soft:   whether to add an entry to the metadata indicating the schematic was created with Litemapy
        :param gzipped:     whether to compress the NBT content with gzip (this is the normal behavior)
        :param byteorder:   endianness of NBT numbers (either "little" or "big", default is "big")

        :raises ValueError: if this schematic does not have any region
        """
        ...

    def to_nbt(self, save_soft: bool = ...) -> Compound:
        """
        Write the schematic to an NBT tag.

        :param save_soft:   whether to add an entry to the metadata indicating the schematic was created with Litemapy

        :rtype: ~nbtlib.tag.Compound

        :raises ValueError: if this schematic does not have any region
        """
        ...

    @deprecated_name("fromnbt")
    @staticmethod
    def from_nbt(nbt: Compound) -> Schematic:
        """
        Read a schematic from an NBT tag.

        :param nbt: a schematic serialized as an NBT tag

        :rtype:     Schematic

        :raises CorruptedSchematicError: if the schematic tag is malformed
        """
        ...

    @deprecated_name("updatemeta")
    def update_metadata(self) -> None:
        """
        Update this schematic's metadata (set the modified time to the current time).
        """
        ...

    @staticmethod
    def load(file_path) -> Schematic:
        """
        Read a schematic from a file.

        :param file_path:   the filesystem path to the file to load

        :rtype:             Schematic

        :raises CorruptedSchematicError: if the schematic file is malformed in any way
        """
        ...

    @property
    def regions(self) -> DiscriminatingDictionary:
        """
        The regions in this schematic, as a dictionary.
        This is a read only property, and it is not possible to replace this dictionary.
        It can however be edited, as long as the suitable types are used.
        Using an incorrect type will raise a :class:`~litemapy.storage.DiscriminationError`.
        """
        ...

    @property
    def width(self) -> int:
        """
        The width of this Schematic's bounding box.
        See :ref:`Coordinate systems <coordinates>`.
        This property is read-only.
        """
        ...

    @property
    def height(self) -> int:
        """
        The height of this Schematic's bounding box.
        See :ref:`Coordinate systems <coordinates>`.
        This property is read-only.
        """
        ...

    @property
    def length(self) -> int:
        """
        The length of this Schematic's bounding box.
        See :ref:`Coordinate systems <coordinates>`.
        This property is read-only.
        """
        ...

    @property
    def preview(self) -> IntArray: ...
    @preview.setter
    def preview(self, value) -> None: ...

class Region:
    """
    Represents a schematic region.
    """

    __x: int
    __y: int
    __z: int
    __width: int
    __height: int
    __length: int
    __palette: list[BlockState]
    __blocks: np.ndarray[np.uint32, Any]
    __entities: list[Entity]
    __block_ticks: list[Compound]
    __fluid_ticks: list[Compound]
    __tile_entities: list[TileEntity]
    def __init__(self, x, y, z, width, height, length) -> None:
        """
        :param x:       the X coordinate of the region in the schematic
        :param y:       the Y coordinate of the region in the schematic
        :param z:       the Z coordinate of the region in the schematic
        :param width:   the size of the region along the x-axis (can be negative!)
        :param height:  the size of the region along the y-axis (can be negative!)
        :param length:  the size of the region along the z-axis (can be negative!)

        :raises ValueError: if either width, height or length is 0
        """
        ...

    def to_nbt(self) -> Compound:
        """
        Write this region to an NBT tag.

        """
        ...

    def to_sponge_nbt(
        self, mc_version: int = ..., gzipped: bool = ..., endianness: str = ...
    ) -> nbtlib.nbt.File:
        """
        Returns the Region as an NBT Compound file that conforms to the Sponge Schematic Format (version 2) used by mods
        like WorldEdit.
        Check `the file format specification <https://github.com/SpongePowered/Schematic-Specification>`_
        for more information.

        :param mc_version:  Minecraft data version that is being emulated
                            (https://minecraft.wiki/w/Data_version).
                            Should not be critical for newer versions of Minecraft.
        :param gzipped:     Whether the NBT Compound file should be compressed
                            (WorldEdit only works with gzipped files).
        :param endianness:  Endianness of the resulting NBT Compound file
                            ('big' or 'little', WorldEdit only works with big endian files).

        :returns:           The Region represented as a Sponge Schematic NBT Compound file.
        """
        ...

    @staticmethod
    def from_sponge_nbt(nbt: Compound) -> tuple[Region, int]:
        """
        Returns a Litematica Region based on an NBT Compound that conforms to the Sponge Schematic Format (version 2)
        used by mods like WorldEdit.
        Check `the file format specification <https://github.com/SpongePowered/Schematic-Specification>`_
        for more information.

        :param nbt: The Sponge schematic NBT Compound.

        :returns:   a Litematica Region built from the Sponge schematic
                    and the Minecraft data version that the Sponge schematic was created for.
        """
        ...

    def to_structure_nbt(
        self, mc_version=..., gzipped=..., byteorder=...
    ) -> nbtlib.nbt.File:
        """
        Returns the Region as an NBT Compound file that conforms to Minecraft's structure NBT files.

        :param mc_version:  Minecraft data version that is being emulated
                            (https://minecraft.wiki/w/Data_version).
                            Should not be critical for newer versions of Minecraft.
        :param gzipped:     Whether the NBT Compound file should be compressed
                            (Vanilla Minecraft only works with gzipped files).
        :param byteorder:   Endianness of the resulting NBT Compound file
                            ('big' or 'little', Vanilla Minecraft only works with big endian files).

        :returns:           The Region represented as a Minecraft structure NBT file.
        """
        ...

    @staticmethod
    def from_structure_nbt(structure: Compound) -> tuple[Region, str]:
        """
        Returns a Litematica Region based on an NBT Compound that conforms to Minecraft's structure NBT files.

        :param structure:   The Minecraft structure NBT Compound.

        :returns:           A Litematica Region built from the Minecraft structure
                            and the Minecraft data version that the structure was created for
        """
        ...

    def __getitem__(self, position: tuple[int, int, int]) -> BlockState: ...
    @deprecated(
        "Region.getblock() is deprecated. Use array style syntax instead: region[x, y, z]"
    )
    def getblock(self, x: int, y: int, z: int) -> BlockState: ...
    def __setitem__(
        self, position: tuple[int, int, int], block: BlockState
    ) -> None: ...
    @deprecated(
        "Region.setblock() is deprecated. Use array style syntax instead: region[x, y, z]"
    )
    def setblock(self, x: int, y: int, z: int, block: BlockState):  # -> None:
        ...
    def __contains__(self, block: BlockState) -> bool: ...
    @deprecated_name("getblockcount")
    def count_blocks(self) -> int:
        """
        Counts the number of blocks in the region.

        :returns: the number of non-air blocks in the region
        """
        ...

    @deprecated_name("getvolume")
    def volume(self) -> int:
        """
        Computes this region's volume.

        :returns: this region volume in blocks
        """
        ...

    @deprecated_name("fromnbt")
    @staticmethod
    def from_nbt(nbt: Compound) -> Region:
        """
        Read a region from an NBT tag.

        :param nbt: an NBT tag to read the region from
        """
        ...

    @deprecated_name("minschemx")
    def min_schem_x(self) -> int:
        """
        :returns:   the minimum X coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("maxschemx")
    def max_schem_x(self) -> int:
        """
        :returns:   the maximum X coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("minschemy")
    def min_schem_y(self) -> int:
        """
        :returns:   the minimum Y coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("maxschemy")
    def max_schem_y(self) -> int:
        """
        :returns:   the maximum Y coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("minschemz")
    def min_schem_z(self) -> int:
        """
        :returns:   the minimum Z coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("maxschemz")
    def max_schem_z(self) -> int:
        """
        :returns:   the maximum Z coordinate of this region in the schematics coordinate system
        """
        ...

    @deprecated_name("minx")
    def min_x(self) -> int:
        """
        :returns:   the minimum X coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("maxx")
    def max_x(self) -> int:
        """
        :returns:   the maximum X coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("miny")
    def min_y(self) -> int:
        """
        :returns:   the minimum Y coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("maxy")
    def max_y(self) -> int:
        """
        :returns:   the maximum Y coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("minz")
    def min_z(self) -> int:
        """
        :returns:   the minimum Z coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("maxz")
    def max_z(self) -> int:
        """
        :returns:   the maximum Z coordinate of this region in its own coordinate system
        """
        ...

    @deprecated_name("xrange")
    def range_x(self) -> range:
        """
        :returns:   the range of coordinates this region contains along its X axis
        """
        ...

    @deprecated_name("yrange")
    def range_y(self) -> range:
        """
        :returns:   the range of coordinates this region contains along its Y axis
        """
        ...

    @deprecated_name("zrange")
    def range_z(self) -> range:
        """
        :returns:   the range of coordinates this region contains along its Z axis
        """
        ...

    @deprecated_name("allblockpos")
    def block_positions(self) -> Generator[tuple[int, int, int], None, None]:
        """
        :returns:   an iterator over the coordinates this region contains in its own coordinate system
        """
        ...

    @property
    def x(self) -> int:
        """
        The X coordinate of the region within the schematic's coordinate system.
        This property is read only.
        """
        ...

    @property
    def y(self) -> int:
        """
        The Y coordinate of the region within the schematic's coordinate system.
        This property is read only.
        """
        ...

    @property
    def z(self) -> int:
        """
        The Z coordinate of the region within the schematic's coordinate system.
        The property is read only.
        """
        ...

    @property
    def width(self) -> int:
        """
        The width of the region.
        This property is read only.
        """
        ...

    @property
    def height(self) -> int:
        """
        The height of the region.
        This property is read only.
        """
        ...

    @property
    def length(self) -> int:
        """
        The length of the region.
        This property is read only.
        """
        ...

    @property
    def entities(self) -> list[Entity]:
        """
        The entities within the region.
        """
        ...

    @property
    def tile_entities(self) -> list[TileEntity]:
        """
        The tile entities within the region.
        """
        ...

    @property
    def block_ticks(self) -> list[Compound]: ...
    @property
    def fluid_ticks(self) -> list[Compound]: ...
    @property
    def palette(self) -> tuple[BlockState, ...]:
        """
        The palette used to store blocks within the region.
        Each entry in the palette is assured to be unique.
        Expected the first palette entry which is always "minecraft:air",
        each entry is assured to have at least one instance in the region.
        """
        ...

    def as_schematic(
        self,
        name: str = ...,
        author: str = ...,
        description: str = ...,
        mc_version: int = ...,
    ) -> Schematic:
        """
        Creates a schematic that contains that region at the origin.

        :param name:        a name for both the region and the schematic
        :param author:      an author for the schematic
        :param description: a description for the schematic
        :param mc_version:  The Minecraft data version (you are unlikely to ever need to use this)
        """
        ...

    def filter(self, function: Callable[[BlockState], BlockState]) -> None:
        """
        Replaces all occurrences of :class:`BlockState` with others by providing a mapping function.
        This method works with the palette directly and the mapping function is therefore only called
        once per block state type in the region, and not for every position.
        This is a lot faster than manually iterating over region coordinates.

        :param function: a mapping function
        """
        ...

    def replace(self, replace: BlockState, replace_with: BlockState) -> None:
        """
        Replace all occurrences of a :class:`BlockState` with another.
        This method works with the palette directly, in O(1) time,
        and is therefore a lot more efficient than looping over the content.

        :param replace:         the blockstate to replace
        :param replace_with:    a new blockstate to replace the old one with
        """
        ...

AIR = BlockState("minecraft:air")

class CorruptedSchematicError(Exception): ...
