"""
This type stub file was generated by pyright.
"""

from nbtlib import LongArray
from typing import Any, Callable, Generator, Optional

class LitematicaBitArray:
    size: int
    nbit: int
    array: list[int]
    __mask: int
    def __init__(self, size: int, nbits: int) -> None:
        ...
    
    @staticmethod
    def from_nbt_long_array(arr: LongArray, size: int, nbits: int) -> LitematicaBitArray:
        ...
    
    def __getitem__(self, index) -> int:
        ...
    
    def __setitem__(self, index: int, value: int) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> Generator[int, None, None]:
        ...
    
    def __reversed__(self) -> LitematicaBitArray:
        ...
    
    def __contains__(self, value: int) -> bool:
        ...
    


ValidatorFunction = Callable[[Any, Any], tuple[bool, str]]
ReactionFunction = Callable[[Any, Any], None]
class DiscriminatingDictionary(dict):
    validator: ValidatorFunction
    on_add: Optional[ReactionFunction]
    on_remove: Optional[ReactionFunction]
    def __init__(self, validator: ValidatorFunction, *args, onadd: Optional[ReactionFunction] = ..., onremove: Optional[ReactionFunction] = ..., **options) -> None:
        """
        :params validator:  a function that takes as argument a key and an item and returns a tuple (canstore, msg)
                            canstore must be a boolean, True if the item is accepted, and False otherwise
                            if canstore is false, msg will be used as the error message
        :param onadd:       an optional function that gets called when an item is added to the dictionary,
                            with the key and item as arguments.
                            onadd is not called for the values that might have been passed in the constructor.
        """
        ...
    
    def validate(self, key: Any, item: Any) -> None:
        ...
    
    def __setitem__(self, key: Any, item: Any) -> None:
        ...
    
    def __delitem__(self, key: Any) -> None:
        ...
    
    def setdefault(self, key: Any, *args) -> Optional[Any]:
        ...
    
    def update(self, other: dict, **kwargs) -> None:
        ...
    
    def pop(self, key: Any) -> None:
        ...
    
    def popitem(self) -> None:
        ...
    
    def clear(self) -> None:
        ...
    


class DiscriminationError(Exception):
    ...


